#!/bin/sh
DOMAIN="$1"

# set up nginx configuration
BASE_DIR=/home/judge/hw4/preflight
NGINX_DIR=/usr/local/etc/nginx

rm "$NGINX_DIR"/nginx.conf
cp "$BASE_DIR"/src/nginx.conf "$NGINX_DIR"/nginx.conf

mkdir "$NGINX_DIR"/sites/
cp "$BASE_DIR"/src/default "$NGINX_DIR"/sites/default
sed -i 's/my-template-domain-name/"$DOMAIN"/g' "$NGINX_DIR"/sites/default

# get certs and restart nginx
"$BASE_DIR"/src/get-certs.sh "$DOMAIN"
